name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle 8.2
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.2

      - name: Create Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Verify Gradle Version
        run: ./gradlew --version

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk